### PR TITLE
Update index.html

### PR DESCRIPTION
**Pull request by imayushdas**
**Description**

Changes proposed in this pull request:

- ...
- ...
- ...

**Related issue(s)**

### CODE REVIEW

**Comment by derberg** [comment]
@imayushdas hey, and thanks a bunch for your contribution. Could you please adjust the description of the PR and commit message to indicate what and why you are fixing.

Please also sign the CLA

**Comment by a-thaler** [comment]
@imayushdas Can you please sign the CLA to get this forward, thanks a lot

**Pull request closed without merging**
